//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasSistemasUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int ProductoID { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<int> Stock { get; set; }
        public int TipoProductoID { get; set; }
    
        public virtual TipoProducto TipoProducto { get; set; }
    }
}
